name: Update README with activity

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: FilippoPY
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
